---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bridge-factory-near
  description: Factory on NEAR
  tags:
    - contract
    - near
  links: []
  annotations:
    aurora.dev/security-tier: "1"
spec:
  owner: bridge-team
  type: contract
  lifecycle: production
  system: bridge-connectors
  deployedAt:
    - contract:near/mainnet/factory.bridge.near
  interactsWith: []
  subcomponentOf: bridge-erc20-connector
